### ISSUE TITLE
Measure Cost Library Duplication

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#27]
It would seem that each reference to the Arrowhead PY22 Measure Cost Library causes another entry in both the navigation pane as well as the drop list selector in the audit.

<img width="858" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/6c5cfb59-56d9-4f4e-8fc0-b9c11ad7a0c2">

<img width="442" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/57d44880-7736-4fb4-b689-95dff20c6b0e">

**Comment by eckmanwe** [comment]
This appears to be the remnant of a previously resolved issue. All but one library set to Active = no. No longer showing reference to audits (# Audits = 0). Ready for deletion at the users discretion.  

Please let us know if you are able to recreate. Otherwise, we consider this issue resolved.

**Comment by fishbaugher** [comment]
Concur that the measure cost drop list is not currently showing the anomaly.
