### ISSUE TITLE
Window retrofit field alignment

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#28]
This just looks odd.  Fields work ok.

<img width="413" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/d1b2598e-3131-46c7-a7d3-c15584121327">

**Comment by eckmanwe** [comment]
Updated 2/29. Please see current form.

![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/eca88bcc-32fa-4cfa-82e2-e87d81b4bc22)

**Comment by fishbaugher** [comment]
Bill, thanks for the screen shot.

Looks like this has been fixed!  Thanks.
