### ISSUE TITLE
The door/wall drop list broken.  Does not show West wall

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#29]
There are 4 walls defined for this house.  Only three show in the drop list.

<img width="557" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/9f1c3cfc-6a1d-4b4d-9dcc-432b1a9b6697">

**Comment by eckmanwe** [comment]
Audit shown no longer appears on WA-MN for investigation.  

![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/3760760c-b7db-4088-9aa0-9b6daa5e448c)
  

Audit 987654321-01 only includes (3) walls.  
![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/e73edc99-d229-48bc-a64d-e7f10df80c02)


**Please confirm that subject wall is not "Buffered". If so, then omitted from list as expected.**

**Comment by fishbaugher** [comment]
Assume this was the buffered wall problem and close unless this shows to be a problem again.
