### ISSUE TITLE
Inspected check mark not connected on work order report

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#32]
Each work order measure has an Inspected check box area in the report:

<img width="925" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/03724b49-d5cc-4118-a488-b439772e95be">

But it does not appear to be connected to the work order inspection status.  Is this by design?  Is there supposed to be an inspected checkmark at the work order measure level, or is this a paper only check mark area?

<img width="867" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/38a9e995-03e3-4fa3-a21b-78e45f5b4882">

**Comment by JdeLarbre218** [comment]
I do believe this is a paper only checkmark

this process exists already with old WA 8.x as we use the checkmark on printed copies but not in the app itself.
![oldWAcheckbox](https://github.com/fishbaugher/WAweb-Issues/assets/162179036/d9d732dc-4d94-40ad-8c66-614be4db807f)
Here is a completed job but the box remains unchecked until it is physically marked on at QCI with the original paperwork held with the file.

**Comment by fishbaugher** [comment]
This is working the same as the v8  paper only inspected checkmark area.
