### ISSUE TITLE
HVAC - Operational Tests - Listed/Rated Heat Rise: Cannot use (-)(/)(,)

### ISSUE THREAD

**Issue by JdeLarbre218** [fishbaugher/WAweb-Issues#38]
cannot use hyphen for listed/rated heat rise, period works

**Comment by JdeLarbre218** [comment]
Additionally, using a period with numbers ending in 0 reverts to a number with decimal.
![listed rated heat rise](https://github.com/fishbaugher/WAweb-Issues/assets/162179036/cb275268-2c8e-4c1d-8e3e-3be9a9b7402c)

**Comment by BrianaParrBaker** [comment]
A couple other issues in the Operational Tests:
-Flue Gas Temp has a minimum of 100 degrees (doesn’t work for many high efficiency furnaces)
-when you tab, it goes across (jumping between Audit and Inspection). It would be more helpful to go straight down the column.

**Comment by eckmanwe** [comment]
We do not recommend attempting to cover multiple topics with a single issue. For example, do not lump valid flue gas temperatures in with Heat Rise.

**Comment by BrianaParrBaker** [comment]
Thanks. I have created separate issues.

**Comment by fishbaugher** [comment]
See #57
