### ISSUE TITLE
HVAC: MISSING heating systems

### ISSUE THREAD

**Issue by JdeLarbre218** [fishbaugher/WAweb-Issues#41]
BIG ONE - Fixed Electric Resistance

plus more . . . 

photos included of WA APP
![Heating sys Wa app](https://github.com/fishbaugher/WAweb-Issues/assets/162179036/2ed9d486-d05a-4933-85ef-5d56987464ea)

photos of WA WEB
![Heating sys web](https://github.com/fishbaugher/WAweb-Issues/assets/162179036/9fd49ee7-5a0a-4545-8df0-f5d4464b296f)

**Comment by eckmanwe** [comment]
"Fixed Electric Resistance" is covered by "Space Heater" with primary fuel = electricity. 

Four of the previous types are all now easily covered by "Space Heater".

![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/6a95570c-746a-4b3c-aa6c-a962221f49bc)

**Comment by JdeLarbre218** [comment]
Thank you for the clarification!
