### ISSUE TITLE
Run error - JSON input validation error (LED Wattage range error)

### ISSUE THREAD

**Issue by BrianaParrBaker** [fishbaugher/WAweb-Issues#50]
This error appeared when attempting to run an audit. This house already had all LED bulbs, so I modeling it as having existing LEDs and got his error. Then I deleted the LED entry and then was able to run the audit. 
Error message: 
![run error](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/9b2363cd-73e6-4ef5-8582-5f4f4226037a)

Lighting page:
![lightng page](https://github.com/fishbaugher/WAweb-Issues/assets/162485966/bc0dc190-dfe8-4bfc-9161-ccc9b35e23df)

**Comment by fishbaugher** [comment]
Existing LED bulbs should have wattage range < 10w available

**Comment by eckmanwe** [comment]
As noted, the primary use case for this is to account for internal loads. Currently lighting does not feed an internal load calculation. Similarly, common use is to omit lighting that will not be considered for replacement.

Existing workaround.

Added for future discussion (incubator #160). Low resulting priority likely.

**Comment by fishbaugher** [comment]
Since the new lamp wattage allows < 10 watts, lets call this one adequate and close the issue.
