### ISSUE TITLE
No filter or sort in Supply Library

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#68]
We need to have some way to navigate with filter or sort on the supply library equipment lists.  Otherwise the only view is reverse chronological by record creation date?  No it is alpha sorted on the equipment name.  So, that leaves munging the name with order information which is not the best workaround.

<img width="743" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/1b03b7ca-fa61-4325-9568-b54dccbb15e1">

**Comment by fishbaugher** [comment]
The original v8 allowed the type-ahead combo box to navigate to a particular record.  It also had sorted lists by description manufactuer or supplier

**Comment by eckmanwe** [comment]
Sorting available by each column.
Please provide clear recommendation.

Supply library navigation is infrequent and limited to few users. If considered for modification, infrequent and limited use will influence priority.

**Comment by fishbaugher** [comment]
Bill, thanks for pointing that out.

I don't think any new feature is required here given that all the sorts work.

What is missing is the ability to filter, but that is minor.. closing issue.
