### ISSUE TITLE
Refrigerator Source and Life fields missing

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#72]
<img width="679" alt="Untitled 2" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/7b63ef58-a361-4e94-885c-b23a5eee52cb">
<img width="671" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/83600504-4673-4c0f-9108-7bbecffcb8ea">

**Comment by fishbaugher** [comment]
The Life field is also missing.  I suspect that field is not used, rather the audit form has lifetime of replacement.
<img width="459" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/41c2bf21-e793-4bf5-9821-cabc21526455">

**Comment by eckmanwe** [comment]
Life is irrelevant as it is controlled by the Measure Costs library.

What I see is that there is likely no Suppliers (Agency - Contacts) for the selected Agency to which this Supply Library is linked. As such, the "Supplier" combo box is ghosted. Enter Supplier(s) and you can link them in the Supply Library.

![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/054a3662-0bbf-465c-99f8-d718faab6b84)

![image](https://github.com/fishbaugher/WAweb-Issues/assets/98035802/ec3550ee-c3a5-475a-ac9b-c526ee3d6a82)


No workaround required.

**Comment by fishbaugher** [comment]
Agreed, this is one field that is really superfluous in v8.x
