### ISSUE TITLE
Incorrect "complete current row" warning in Defined Measure Library

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#75]
When entering a new Defined Measure Library entry, on the first press of the Add Detail button in the Materials/Labor Detail area I got (one time out of 20 or so new records):

<img width="893" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/be291ab7-a3af-4aa7-9e8a-c5fa40d6c8dc">

This is not repeatable.  Intermittent.

Work around is good, just press OK and continue.

**Comment by eckmanwe** [comment]
no action planned.
