### ISSUE TITLE
MulTEA new audit server error

### ISSUE THREAD

**Issue by fishbaugher** [fishbaugher/WAweb-Issues#88]
After entering a new MulTEA audit with agency admin logon and pressing the Apply button, I get:

<img width="804" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/b6040ddf-bd71-484f-9f40-73623c0c77b0">

Question: Should we expect MulTEA to work?

I get the same error on each new logon and first visit to the MulTEA form.  Also, on each visit to the form, when navigating away (after no data entry) I get:

<img width="501" alt="Untitled" src="https://github.com/fishbaugher/WAweb-Issues/assets/479175/4b9d1300-35a1-4289-ac08-5f30d4151ce6">

Not sure how to set the priority on this one because I am  not sure if MN plans to use MulTEA.

**Comment by bgoldenMN** [comment]
Minnesota does not  plan to use MulTEA at this time.  For multifamily, we will continue to use EAQuip for PY 24

**Comment by fishbaugher** [comment]
Ben, so lets close this issue for now and we can return to MulTEA if/when MN decides to use it.
