### ISSUE TITLE
Lighting error (Existing only)

### ISSUE THREAD

**Issue by joe-shade** [fishbaugher/WAweb-Issues#92]
![Lights tool tip](https://github.com/fishbaugher/WAweb-Issues/assets/167787157/4bf18edc-ac7f-4662-8dff-60e2ef632e83)

![Lights run error](https://github.com/fishbaugher/WAweb-Issues/assets/167787157/0c948d55-bf7d-448b-8e7c-4c41fc54e6c4)

If the existing lightbulb is less than 10 watts it causes a run error.  The tool tip says the field is 1 - 250.  This is an issue with CFL 40w equivalent bulbs and modeling of LED bulbs that are 60w and 40w equivalents for baseload.

**Comment by joe-shade** [comment]
I can't seem to attach labels to this.  I work at AEOA and put an audit in.  The other errors I found already have issues created.

**Comment by JdeLarbre218** [comment]
Also found this issue when trying to replace bulbs that are existing under 10w

Additionally, there is a closed topic that covers this and explains a workaround

**Comment by eckmanwe** [comment]
Easy workaround. Increase existing and replacement watts by the same amount (in this case 1watt). Checked sensitivity, and the calculations work the same with the same savings regardless.

Noted for updated Tooltip. Schema change unlikely or long delay as it affects the WAweb-API schema.
