### ISSUE TITLE
MHEA cumulative SIR seems wrong

### ISSUE THREAD

**Issue by joe-shade** [fishbaugher/WAweb-Issues#94]
![MHEA recommended measures](https://github.com/fishbaugher/WAweb-Issues/assets/167787157/794e92e4-770c-4cf1-b634-ccc4e520b9d4)

This is a completed audit in MHEA, and the cumulative SIR of 0.34 for the SIR measures listed above has to be wrong.  The furnace alone should be able to overcome the crew travel and even the health and safety if it is accidentally included.  

[Audit1146-mhearecommended.pdf](https://github.com/fishbaugher/WAweb-Issues/files/15120467/Audit1146-mhearecommended.pdf)

I have included the pdf of run

**Comment by joe-shade** [comment]
Here is another audit

![MHEA recommended measures 752935](https://github.com/fishbaugher/WAweb-Issues/assets/167787157/64bdd1c5-d1d0-4cfb-a8bf-11df09e47f75)

Desktop with similar numbers has a cumulative of 3.4

It seems that the cumulative is taking the savings per year and dividing it by the cumulative measure cost of the SIR measures without taking into account the number of years each of those measures is supposed to cover.

**Comment by eckmanwe** [comment]
Noted and under investigation. May impact measure selection/project approval - High Priority.  

Reference issue number: Engine #696

**Comment by eckmanwe** [comment]
Issue resolved - update 10.05.016.

Please rerun audit. Expected cumulative SIR ~4.25

**Comment by joe-shade** [comment]
Cumulative SIR for the first project is now 4.83
Cumulative SIR for the second project is now 4.05
Both seem close to your stated expected cumulative SIR of 4.25
